# SPDX-License-Identifier: MIT
#
# init
#
# Copyright (C) 2025-present Farhan Kurnia Pratama
#
# GitHub     : https://github.com/farhnkrnapratma/tuxfetch
# Maintainer : Farhan Kurnia Pratama <farhnkrnapratma@gmail.com>
#
github: farhnkrnapratma
open_collective: farhnkrnapratma
custom: ['paypal.me/farhnkrnapratma']
