name: Makefile CI

on:
  push:
    branches:
      - main
      - dev
    paths:
      - Makefile
      
  pull_request:
    branches:
      - main
      - dev
    paths:
      - Makefile

jobs:
  makefile-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v4

    - name: Do Install
      uses: make do-install
    
    - name: Do Config
      uses: make do-install

    - name: Install
      uses: make install

    - name: Clean Install
      uses: make clean-install

    - name: Update
      uses: make update

    - name: Clean Update
      uses: make clean-update
    
    - name: Uninstall
      uses: make uninstall

    - name: Clean Uninstall
      uses: make clean-uninstall
