name: Makefile CI

on:
  push:
    branches:
      - main
      - dev
    paths:
      - Makefile
      
  pull_request:
    branches:
      - main
      - dev
    paths:
      - Makefile

jobs:
  makefile-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Install
        run: make install

      - name: Clean Install
        run: make clean-install

      - name: Update
        run: make update

      - name: Clean Update
        run: make clean-update
    
      - name: Uninstall
        run: make uninstall

      - name: Clean Uninstall
        run: make clean-uninstall
