# SPDX-License-Identifier: MIT
#
# tuxfetch
#
# Copyright (C) 2025-present Farhan Kurnia Pratama
#
# GitHub     : https://github.com/farhnkrnapratma/tuxfetch
# Maintainer : Farhan Kurnia Pratama <farhnkrnapratma@gmail.com>
#
name: Tuxfetch CI

on:
  push:
    branches:
      - main
      - dev
    paths:
      - tuxfetch
      
  pull_request:
    branches:
      - main
      - dev
    paths:
      - tuxfetch
      
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint using ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          args: --exclude=SC1091,SC2154 --source-path=$HOME/.config/tuxfetch/init tuxfetch